services:
  nest-auth-app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      nest-auth-redis:
        condition: service_healthy
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./typeorm.config.ts:/usr/src/app/typeorm.config.ts
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  nest-auth-redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nest-auth-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  pgdata:
  redisdata:
